on: [push, pull_request]
name: Test

env:
  PACT_BROKER_BASE_URL: https://testdemo.pactflow.io
  PACT_BROKER_TOKEN: ${{ secrets.PACT_BROKER_TOKEN }}
  REACT_APP_API_BASE_URL: http://localhost:8080
  APP_SHA: ${{ github.sha }}
  APP_BRANCH: ${{ github.ref }}
  LD_LIBRARY_PATH: /tmp
  PACT_GO_LIB_DOWNLOAD_PATH: /tmp
  LOG_LEVEL: trace

jobs:
  test:
    strategy:
      matrix:
        go-version: [1.17.x, 1.18.x]
        # os: [ubuntu-latest, macos-latest, windows-latest]
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go-version }}
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Test
        run: make
      - uses: actions/upload-artifact@v3
        with:
          name: Upload plugin logs
          path: ~/.pact/plugins/**/plugin.log
        if: ${{ always() }}
