on: [push, pull_request]
name: Test
jobs:
  test:
    strategy:
      matrix:
        go-version: [1.15.x, 1.14.x, 1.13.x]
        # os: [ubuntu-latest, macos-latest, windows-latest]
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - name: Set Golang shared lib directory for GH Actions
      run: |
        echo "LD_LIBRARY_PATH=/tmp" >> $GITHUB_ENV
        echo "PACT_GO_LIB_DOWNLOAD_PATH=/tmp" >> $GITHUB_ENV
    - name: Install Go
      uses: actions/setup-go@v2
      with:
        go-version: ${{ matrix.go-version }}
    - name: Checkout code
      uses: actions/checkout@v2
    # TODO: problem for another day
    # - name: Run Snyk to check for vulnerabilities
    #   uses: snyk/actions/golang@master
    #   env:
    #     SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
    - name: Test
      run: make
      env:
        PACT_BROKER_TOKEN: '${{ secrets.PACT_BROKER_TOKEN }}'